from sqlalchemy import Column, Integer, String, Boolean, DateTime, Text, ForeignKey, Index
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from app.core.database import Base
import uuid

class User(Base):
    __tablename__ = "users"
    
    id = Column(Integer, primary_key=True, index=True)
    uuid = Column(String(36), unique=True, default=lambda: str(uuid.uuid4()), index=True)
    email = Column(String(255), index=True, nullable=False)  # Removed unique constraint for multi-tenant
    username = Column(String(100), index=True, nullable=True, default=None)  # Removed unique constraint for multi-tenant
    hashed_password = Column(String(255), nullable=False)
    first_name = Column(String(100), nullable=False)
    last_name = Column(String(100), nullable=False)
    is_active = Column(Boolean, default=True, index=True)
    is_verified = Column(Boolean, default=False, index=True)
    role_id = Column(Integer, ForeignKey("roles.id"), nullable=False, index=True)
    product_id = Column(String(100), nullable=True, index=True, default=None)  # Auto-generated by backend
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())
    last_login = Column(DateTime(timezone=True))
    login_attempts = Column(Integer, default=0)
    locked_until = Column(DateTime(timezone=True))
    
    # Relationships
    role = relationship("Role", back_populates="users")
    refresh_tokens = relationship("RefreshToken", back_populates="user", cascade="all, delete-orphan")
    password_resets = relationship("PasswordReset", back_populates="user", cascade="all, delete-orphan")
    
    # Composite indexes and constraints for multi-tenant
    __table_args__ = (
        Index('idx_user_product_active', 'product_id', 'is_active'),
        Index('idx_user_email_active', 'email', 'is_active'),
        Index('idx_user_role_product', 'role_id', 'product_id'),
        Index('idx_user_email_product', 'email', 'product_id'),  # For unique email per product
        Index('idx_user_username_product', 'username', 'product_id'),  # For unique username per product
    )

class Role(Base):
    __tablename__ = "roles"
    
    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(50), index=True, nullable=False)  # Removed unique constraint for multi-tenant
    description = Column(Text)
    permissions = Column(Text)  # JSON string of permissions
    product_id = Column(String(100), nullable=True, index=True)  # Multi-tenant support
    is_active = Column(Boolean, default=True, index=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    
    # Relationships
    users = relationship("User", back_populates="role")
    
    # Composite unique constraint for multi-tenant
    __table_args__ = (
        Index('idx_role_name_product', 'name', 'product_id'),
    )

class RefreshToken(Base):
    __tablename__ = "refresh_tokens"
    
    id = Column(Integer, primary_key=True, index=True)
    token = Column(String(255), unique=True, index=True, nullable=False)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    product_id = Column(String(100), nullable=True, index=True)  # Multi-tenant support
    expires_at = Column(DateTime(timezone=True), nullable=False)
    is_revoked = Column(Boolean, default=False, index=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    
    # Relationships
    user = relationship("User", back_populates="refresh_tokens")
    
    # Indexes for performance
    __table_args__ = (
        Index('idx_refresh_token_user_active', 'user_id', 'is_revoked'),
        Index('idx_refresh_token_expires', 'expires_at'),
        Index('idx_refresh_token_product', 'product_id', 'is_revoked'),
    )

class PasswordReset(Base):
    __tablename__ = "password_resets"
    
    id = Column(Integer, primary_key=True, index=True)
    token = Column(String(255), unique=True, index=True, nullable=False)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=False, index=True)
    product_id = Column(String(100), nullable=True, index=True)  # Multi-tenant support
    expires_at = Column(DateTime(timezone=True), nullable=False)
    is_used = Column(Boolean, default=False, index=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    
    # Relationships
    user = relationship("User", back_populates="password_resets")
    
    # Indexes for performance
    __table_args__ = (
        Index('idx_password_reset_token_used', 'token', 'is_used'),
        Index('idx_password_reset_expires', 'expires_at'),
        Index('idx_password_reset_product', 'product_id', 'is_used'),
    ) 