"""Make username and product_id nullable and default to None in users table

Revision ID: 3d9b2b198496
Revises: 
Create Date: 2025-07-11 18:59:47.624024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d9b2b198496'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_password_resets_unused_partial', table_name='password_resets', postgresql_where='(is_used = false)')
    op.drop_index('idx_refresh_tokens_active_partial', table_name='refresh_tokens', postgresql_where='(is_revoked = false)')
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'product_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_index('idx_users_active_partial', table_name='users', postgresql_where='(is_active = true)')
    op.drop_index('idx_users_locked_partial', table_name='users', postgresql_where='(locked_until IS NOT NULL)')
    op.drop_index('idx_users_unverified_partial', table_name='users', postgresql_where='(is_verified = false)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_users_unverified_partial', 'users', ['email', 'created_at'], unique=False, postgresql_where='(is_verified = false)')
    op.create_index('idx_users_locked_partial', 'users', ['id', 'locked_until'], unique=False, postgresql_where='(locked_until IS NOT NULL)')
    op.create_index('idx_users_active_partial', 'users', ['email', 'username'], unique=False, postgresql_where='(is_active = true)')
    op.alter_column('users', 'product_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.create_index('idx_refresh_tokens_active_partial', 'refresh_tokens', ['user_id', 'expires_at'], unique=False, postgresql_where='(is_revoked = false)')
    op.create_index('idx_password_resets_unused_partial', 'password_resets', ['user_id', 'expires_at'], unique=False, postgresql_where='(is_used = false)')
    # ### end Alembic commands ### 