"""Add organizational hierarchy and attendance tables

Revision ID: c66e6ec0e7f3
Revises: 3d9b2b198496
Create Date: 2025-08-01 09:20:08.393975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c66e6ec0e7f3'
down_revision = '3d9b2b198496'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_password_resets_product', table_name='password_resets')
    op.create_index('idx_password_reset_product', 'password_resets', ['product_id', 'is_used'], unique=False)
    op.create_index(op.f('ix_password_resets_product_id'), 'password_resets', ['product_id'], unique=False)
    op.drop_index('idx_refresh_tokens_product', table_name='refresh_tokens')
    op.create_index('idx_refresh_token_product', 'refresh_tokens', ['product_id', 'is_revoked'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_product_id'), 'refresh_tokens', ['product_id'], unique=False)
    op.drop_index('idx_roles_product', table_name='roles')
    op.create_index('idx_role_name_product', 'roles', ['name', 'product_id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=False)
    op.create_index(op.f('ix_roles_product_id'), 'roles', ['product_id'], unique=False)
    op.create_index('idx_user_email_product', 'users', ['email', 'product_id'], unique=False)
    op.create_index('idx_user_username_product', 'users', ['username', 'product_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_user_username_product', table_name='users')
    op.drop_index('idx_user_email_product', table_name='users')
    op.drop_index(op.f('ix_roles_product_id'), table_name='roles')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index('idx_role_name_product', table_name='roles')
    op.create_index('idx_roles_product', 'roles', ['product_id'], unique=False)
    op.drop_index(op.f('ix_refresh_tokens_product_id'), table_name='refresh_tokens')
    op.drop_index('idx_refresh_token_product', table_name='refresh_tokens')
    op.create_index('idx_refresh_tokens_product', 'refresh_tokens', ['product_id'], unique=False)
    op.drop_index(op.f('ix_password_resets_product_id'), table_name='password_resets')
    op.drop_index('idx_password_reset_product', table_name='password_resets')
    op.create_index('idx_password_resets_product', 'password_resets', ['product_id'], unique=False)
    # ### end Alembic commands ### 