"""Add enhanced attendance rules, holidays, and weekend configs

Revision ID: c8b0ad3bc212
Revises: c66e6ec0e7f3
Create Date: 2025-08-04 20:00:22.741031

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c8b0ad3bc212'
down_revision = 'c66e6ec0e7f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_custom_fields_active', table_name='custom_fields')
    op.drop_index('idx_custom_fields_product', table_name='custom_fields')
    op.drop_index('ix_custom_fields_id', table_name='custom_fields')
    op.drop_index('ix_custom_fields_is_active', table_name='custom_fields')
    op.drop_index('ix_custom_fields_product_id', table_name='custom_fields')
    op.drop_table('custom_fields')
    op.drop_index('idx_policy_templates_active', table_name='policy_templates')
    op.drop_index('idx_policy_templates_product', table_name='policy_templates')
    op.drop_index('ix_policy_templates_id', table_name='policy_templates')
    op.drop_index('ix_policy_templates_is_active', table_name='policy_templates')
    op.drop_index('ix_policy_templates_product_id', table_name='policy_templates')
    op.drop_table('policy_templates')
    op.drop_index('idx_policy_custom_values_field', table_name='policy_custom_values')
    op.drop_index('idx_policy_custom_values_policy', table_name='policy_custom_values')
    op.drop_index('ix_policy_custom_values_custom_field_id', table_name='policy_custom_values')
    op.drop_index('ix_policy_custom_values_id', table_name='policy_custom_values')
    op.drop_index('ix_policy_custom_values_policy_id', table_name='policy_custom_values')
    op.drop_table('policy_custom_values')
    op.drop_index('idx_rule_assignments_active', table_name='rule_assignments')
    op.drop_index('idx_rule_assignments_product', table_name='rule_assignments')
    op.drop_index('idx_rule_assignments_target', table_name='rule_assignments')
    op.drop_index('ix_rule_assignments_id', table_name='rule_assignments')
    op.drop_index('ix_rule_assignments_is_active', table_name='rule_assignments')
    op.drop_index('ix_rule_assignments_product_id', table_name='rule_assignments')
    op.drop_index('ix_rule_assignments_rule_id', table_name='rule_assignments')
    op.drop_table('rule_assignments')
    op.add_column('attendance_rules', sa.Column('rule_type', sa.String(length=50), nullable=False))
    op.add_column('attendance_rules', sa.Column('rule_description', sa.Text(), nullable=True))
    op.add_column('attendance_rules', sa.Column('early_departure_threshold_minutes', sa.Integer(), nullable=True))
    op.add_column('attendance_rules', sa.Column('required_work_hours', sa.Integer(), nullable=True))
    op.add_column('attendance_rules', sa.Column('break_duration_minutes', sa.Integer(), nullable=True))
    op.add_column('attendance_rules', sa.Column('weekend_work_allowed', sa.Boolean(), nullable=True))
    op.add_column('attendance_rules', sa.Column('remote_work_allowed', sa.Boolean(), nullable=True))
    op.add_column('attendance_rules', sa.Column('holiday_work_allowed', sa.Boolean(), nullable=True))
    op.add_column('attendance_rules', sa.Column('require_location_validation', sa.Boolean(), nullable=True))
    op.add_column('attendance_rules', sa.Column('allowed_office_locations', sa.Text(), nullable=True))
    op.add_column('attendance_rules', sa.Column('geofence_radius_meters', sa.Integer(), nullable=True))
    op.add_column('attendance_rules', sa.Column('rule_config', sa.Text(), nullable=True))
    op.add_column('attendance_rules', sa.Column('is_default', sa.Boolean(), nullable=True))
    op.add_column('attendance_rules', sa.Column('priority', sa.Integer(), nullable=True))
    op.add_column('attendance_rules', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('idx_attendance_rule_priority', 'attendance_rules', ['priority', 'is_active'], unique=False)
    op.create_index('idx_attendance_rule_type', 'attendance_rules', ['rule_type', 'is_active'], unique=False)
    op.drop_index('idx_password_resets_unused_partial', table_name='password_resets', postgresql_where='(is_used = false)')
    op.drop_index('idx_refresh_tokens_active_partial', table_name='refresh_tokens', postgresql_where='(is_revoked = false)')
    op.drop_index('idx_users_active_partial', table_name='users', postgresql_where='(is_active = true)')
    op.drop_index('idx_users_locked_partial', table_name='users', postgresql_where='(locked_until IS NOT NULL)')
    op.drop_index('idx_users_unverified_partial', table_name='users', postgresql_where='(is_verified = false)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_users_unverified_partial', 'users', ['email', 'created_at'], unique=False, postgresql_where='(is_verified = false)')
    op.create_index('idx_users_locked_partial', 'users', ['id', 'locked_until'], unique=False, postgresql_where='(locked_until IS NOT NULL)')
    op.create_index('idx_users_active_partial', 'users', ['email', 'username'], unique=False, postgresql_where='(is_active = true)')
    op.create_index('idx_refresh_tokens_active_partial', 'refresh_tokens', ['user_id', 'expires_at'], unique=False, postgresql_where='(is_revoked = false)')
    op.create_index('idx_password_resets_unused_partial', 'password_resets', ['user_id', 'expires_at'], unique=False, postgresql_where='(is_used = false)')
    op.drop_index('idx_attendance_rule_type', table_name='attendance_rules')
    op.drop_index('idx_attendance_rule_priority', table_name='attendance_rules')
    op.drop_column('attendance_rules', 'updated_at')
    op.drop_column('attendance_rules', 'priority')
    op.drop_column('attendance_rules', 'is_default')
    op.drop_column('attendance_rules', 'rule_config')
    op.drop_column('attendance_rules', 'geofence_radius_meters')
    op.drop_column('attendance_rules', 'allowed_office_locations')
    op.drop_column('attendance_rules', 'require_location_validation')
    op.drop_column('attendance_rules', 'holiday_work_allowed')
    op.drop_column('attendance_rules', 'remote_work_allowed')
    op.drop_column('attendance_rules', 'weekend_work_allowed')
    op.drop_column('attendance_rules', 'break_duration_minutes')
    op.drop_column('attendance_rules', 'required_work_hours')
    op.drop_column('attendance_rules', 'early_departure_threshold_minutes')
    op.drop_column('attendance_rules', 'rule_description')
    op.drop_column('attendance_rules', 'rule_type')
    op.create_table('rule_assignments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rule_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('target_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('target_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('inheritance_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('effective_from', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('effective_to', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['attendance_rules.id'], name='rule_assignments_rule_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='rule_assignments_pkey')
    )
    op.create_index('ix_rule_assignments_rule_id', 'rule_assignments', ['rule_id'], unique=False)
    op.create_index('ix_rule_assignments_product_id', 'rule_assignments', ['product_id'], unique=False)
    op.create_index('ix_rule_assignments_is_active', 'rule_assignments', ['is_active'], unique=False)
    op.create_index('ix_rule_assignments_id', 'rule_assignments', ['id'], unique=False)
    op.create_index('idx_rule_assignments_target', 'rule_assignments', ['target_type', 'target_id'], unique=False)
    op.create_index('idx_rule_assignments_product', 'rule_assignments', ['product_id'], unique=False)
    op.create_index('idx_rule_assignments_active', 'rule_assignments', ['is_active'], unique=False)
    op.create_table('policy_custom_values',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('policy_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('custom_field_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('field_value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('effective_from', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('effective_to', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['custom_field_id'], ['custom_fields.id'], name='policy_custom_values_custom_field_id_fkey'),
    sa.ForeignKeyConstraint(['policy_id'], ['attendance_rules.id'], name='policy_custom_values_policy_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='policy_custom_values_pkey')
    )
    op.create_index('ix_policy_custom_values_policy_id', 'policy_custom_values', ['policy_id'], unique=False)
    op.create_index('ix_policy_custom_values_id', 'policy_custom_values', ['id'], unique=False)
    op.create_index('ix_policy_custom_values_custom_field_id', 'policy_custom_values', ['custom_field_id'], unique=False)
    op.create_index('idx_policy_custom_values_policy', 'policy_custom_values', ['policy_id'], unique=False)
    op.create_index('idx_policy_custom_values_field', 'policy_custom_values', ['custom_field_id'], unique=False)
    op.create_table('policy_templates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('template_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('base_rules', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('custom_fields', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='policy_templates_created_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='policy_templates_pkey')
    )
    op.create_index('ix_policy_templates_product_id', 'policy_templates', ['product_id'], unique=False)
    op.create_index('ix_policy_templates_is_active', 'policy_templates', ['is_active'], unique=False)
    op.create_index('ix_policy_templates_id', 'policy_templates', ['id'], unique=False)
    op.create_index('idx_policy_templates_product', 'policy_templates', ['product_id'], unique=False)
    op.create_index('idx_policy_templates_active', 'policy_templates', ['is_active'], unique=False)
    op.create_table('custom_fields',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('field_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('field_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('validation_rules', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('default_value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_required', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('depends_on_fields', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('options', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='custom_fields_pkey')
    )
    op.create_index('ix_custom_fields_product_id', 'custom_fields', ['product_id'], unique=False)
    op.create_index('ix_custom_fields_is_active', 'custom_fields', ['is_active'], unique=False)
    op.create_index('ix_custom_fields_id', 'custom_fields', ['id'], unique=False)
    op.create_index('idx_custom_fields_product', 'custom_fields', ['product_id'], unique=False)
    op.create_index('idx_custom_fields_active', 'custom_fields', ['is_active'], unique=False)
    # ### end Alembic commands ### 